"""users table

Revision ID: f7176741c232
Revises: 
Create Date: 2019-06-18 16:40:15.611134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7176741c232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_colors',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
